# Generated by Django 4.1.5 on 2023-01-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='nova',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
