# Generated by Django 4.1.5 on 2023-01-18 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('whatsapp', models.CharField(max_length=13, unique=True)),
                ('divida', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('enviada_em', models.DateTimeField(default=datetime.datetime(2023, 1, 18, 18, 49, 44, 730502), editable=False)),
                ('origem_id', models.UUIDField(editable=False)),
                ('destino_id', models.UUIDField(editable=False)),
                ('texto', models.CharField(editable=False, max_length=700)),
            ],
        ),
    ]
