# Generated by Django 4.1.5 on 2023-01-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_bot_id_alter_cliente_id_alter_mensagem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaMensagem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('usuario_1_id', models.UUIDField(editable=False)),
                ('usuario_2_id', models.UUIDField(editable=False)),
                ('mensagem_id', models.UUIDField()),
            ],
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='enviada_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
