# Generated by Django 4.1.5 on 2023-01-22 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_cliente_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.CreateModel(
            name='ClienteEmCriacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, null=True, unique=True)),
                ('whatsapp', models.CharField(max_length=13, null=True, unique=True)),
                ('divida', models.FloatField(null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
