# Generated by Django 4.1.5 on 2023-01-19 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_ultimamensagem_alter_mensagem_enviada_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimamensagem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
