# Generated by Django 4.1.5 on 2023-01-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_ultimamensagem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimamensagem',
            name='usuario_1_nome',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ultimamensagem',
            name='usuario_2_nome',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
