# Generated by Django 4.1.5 on 2023-01-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_ultimamensagem_usuario_1_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultimamensagem',
            name='mensagem_id',
        ),
        migrations.AddField(
            model_name='ultimamensagem',
            name='texto',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
