# Generated by Django 4.1.5 on 2023-01-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_ultimamensagem_mensagem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultimamensagem',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='ultimamensagem',
            name='usuario_1_id',
        ),
        migrations.RemoveField(
            model_name='ultimamensagem',
            name='usuario_1_nome',
        ),
        migrations.RemoveField(
            model_name='ultimamensagem',
            name='usuario_2_id',
        ),
        migrations.RemoveField(
            model_name='ultimamensagem',
            name='usuario_2_nome',
        ),
    ]
